# ---
# -host: all
# task:
# -name: Clone devstack repository into 
# git:
# repo: 'https://git.openstack.org/openstack-dev/devstack'
# dest: /home/vagrant/
--- 
- 
  hosts: all
  sudo: true
  tasks: 
    # - 
    #   apt: update_cache=yes
    #   name: "update apt cache"
    # - 
    #   apt: "name=apache2 state=present"
    #   name: "install apache"
    # - 
    #   apt: "name=mysql-server state=present"
    #   name: "install mysql"
    # clone Devstack repo with separate git directory
    - git:
        repo:  https://git.openstack.org/openstack-dev/devstack
        dest: /home/vagrant/devstack
        separate_git_dir: /home/vagrant/devstack-examples.git
    - 
      name: Recursively change ownership of the devstack directory to our vagrant owner
      file:
        path: /home/vagrant/devstack
        state: directory
        recurse: yes
        owner: vagrant
        group: vagrant
    - 
      name: "Configure openstack"
      script: /vagrant/openstack_config.sh
      become: yes
      become_user: vagrant
  



#   --- 
# - 
#   hosts: all
#   sudo: true
#   tasks: 
#     - 
#       apt: update_cache=yes
#       name: "update apt cache"
#     - 
#       apt: "name=apache2 state=present"
#       name: "install apache"
#     - 
#       apt: "name=mysql-server state=present"
#       name: "install mysql"
#     # clone Devstack repo with separate git directory
#     - git:
#         repo:  https://git.openstack.org/openstack-dev/devstack
#         dest: /src/devstack
#         separate_git_dir: /src/devstack-examples.git
#   